### ISSUE TITLE
Option to decode unicode string as it is

### ISSUE THREAD

**Issue by ZsgsDesign** [mstrobel/procyon#30]
Right now unicode stirngs would be decompiled to `\u{hex}` like `\u7efc\u5408`.

I believe it would be great if there exists an option to decode those Unicode strings to their original UTF-8 character.

**Comment by wxyu247** [comment]
有个选项"__unicode"输出没有转码的字符串

**Comment by ZsgsDesign** [comment]
> 有个选项"__unicode"输出没有转码的字符串

Looks like commit 3d3fd383897184d48ba6dda8066b2f3957bad602 provides an option `--unicode` for it. Strangly though it says `fixed #105` but #105 does not exist.
