### ISSUE TITLE
com.strobel.reflection.Resolver should return concrete generic type for fields

### ISSUE THREAD

**Issue by BladeWise** [mstrobel/procyon#37]
As far as I could see, the current resolve logic for fields does not return a concrete generic type when it should.

As an example, given the following classes
``` java
    private static final class TestObject extends GenericTestObject<Double> {
    }

    public static class GenericTestObject<T> {
        public List<T> items;

        public T sum(final List<T> values) {
            throw new UnsupportedOperationException();
        }
    }
```
executing `Type.of(TestObject.class).getField("items")` returns `java.util.List<T>` (generic declaration), instead of `java.util.List<java.langDouble>`, which is what I expected.

The underlying field (returned by `Type.of(TestObject.class).getField("items").getRawField()`) holds the correct information through the `getGenericType()` (which is safe to call even for non-generic fields, returning the field `getType()`).

Hence, in my opinion, the following line of code
https://github.com/mstrobel/procyon/blob/fec0d7ae031403b4a56fc2f2fd801fc6d416305a/Procyon.Reflection/src/main/java/com/strobel/reflection/Resolver.java#L775
should call `field.getGenericType()` instead.

Methods behave as expected, invoking the `getGeneric...` versions for parameters, return type and exception types
https://github.com/mstrobel/procyon/blob/fec0d7ae031403b4a56fc2f2fd801fc6d416305a/Procyon.Reflection/src/main/java/com/strobel/reflection/Resolver.java#L785

**Comment by mstrobel** [comment]
Nice find, and thanks for figuring out the fix!
