### ISSUE TITLE
MethodInfo hashCode issue 

### ISSUE THREAD

**Issue by BladeWise** [mstrobel/procyon#42]
The current implementation of `MethodInfo.hashCode` returns the same value for overloaded methods.

As an example, below code
``` java
var abs1 = Type.of(Math.class).getMethod("abs", Types.Integer);
var abs2 = Type.of(Math.class).getMethod("abs", Types.Long);
String.format("%s vs %s:\nAre equal? %s\nHave same hashCode? %s", abs1, abs2, abs1.equals(abs2), abs1.hashCode() == abs2.hashCode());
```
will print
``` console
public static int abs(int) vs public static long abs(long):
Are equal? false
Have same hashCode? true
```
This means that all hash-based collections will never store overloaded methods together, only the last added one.

I noticed that some `MemberInfo`-derived classes override `isEquivalentTo`, without touching `hashCode`.
I suppose that all classes overriding `IsEquivalentTo`, should override `hashCode` accordingly.

**Comment by mstrobel** [comment]
Thanks for the bug report!

```
for (MemberInfo m : Type.of(Math.class).findMembers(MemberType.methodsOnly(), BindingFlags.AllStatic, Type.FilterName, "abs")) {
    System.out.printf("%s = %d%n", m.getBriefDescription(), m.hashCode());
}
```
now yields
```
int abs(int) = -2086594591
double abs(double) = -2086575465
float abs(float) = -2086573285
long abs(long) = -2086594525
```
